services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - '${WORDPRESS_PORT}:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_NAME}'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - 'wordpress_volume:/var/www/html'
  db:
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: '${HOST_DB_ROOT_PASSWORD}'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - 127.0.0.1
        - '--silent'
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - 'db_volume:/var/lib/mysql'
volumes:
  db_volume: null
  wordpress_volume: null
