services:
  vault: #name of service from main docker-compose file
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - "/var/vault/logs:/vault/logs"
      - "/var/vault/file:/vault/file"
      - "/var/vault/config:/vault/config"
    entrypoint: vault server -config=vault.json