services:
  react_js:
    image: react_js_image
    build:
      context: ./ui
      args:
        NODE_ENV: production
        REACT_APP_SERVICE_HOST: http://localhost:8080
    ports:
      - "3000:80"
  node_js:
    image: node_js_iamge
    build:
      context: ./services
      args:
        NODE_ENV: production
        PORT: "80"
    ports:
      - "8080:80"
    